---
- name: Create Apache VMs
  hosts: localhost
  gather_facts: false
  vars:
    vm_name_prefix: "{{ webserver_name }}"
    memory: "{{ webserver_memory }}"
    number_of_vms: "{{ webserver_count }}"
  tasks:
  - import_tasks: create_ovirt_vms.yaml
