---
- name: Create Nagios VM
  hosts: localhost
  gather_facts: false
  vars:
    vm_name_prefix: "{{ nagios_name }}"
    memory: "{{ nagios_memory }}"
    number_of_vms: "{{ nagios_count }}"
    vm_tag: "{{ monitoring_vm_tag }}"
  tasks:
  - import_tasks: create_ovirt_vms.yaml
