---
- name: Create HAProxy VM
  hosts: localhost
  gather_facts: false
  vars:
    vm_name_prefix: "{{ lb_name }}"
    memory: "{{ lb_memory }}"
    number_of_vms: "{{ lb_count }}"
  tasks:
  - import_tasks: create_ovirt_vms.yaml
