---
- name: Create Nagios VM
  hosts: localhost
  gather_facts: false
  vars:
    vm_name_prefix: "{{ nagios_name }}"
    memory: "{{ nagios_memory }}"
    number_of_vms: "{{ nagios_count }}"
  tasks:
  - name: Create Nagios VM
    debug: msg="Creating a Nagios VM"
- import_playbook: create_ovirt_vms.yaml
